server:
  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:springbootssm.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springbootssm
#    key-password: password

spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: 
      auto-index-creation: true
state-machine:
  initial-state: Customer

  states:
    - Customer
    - SalesReview
    - RMReview
    - DocumentReview
    - Credit
    - SDC
    - WelcomeLetter
  end-state: WelcomeLetter

  events:
    - CustomerEvent
    - SalesReviewEvent
    - RMReviewEvent
    - DocumentReviewEvent
    - CreditEvent
    - SDCEvent
    - WelcomeLetterEvent

  transitions:
    - source: Customer
      target: SalesReview
      event: SalesReviewEvent

    - source: SalesReview
      target: RMReview
      event: RMReviewEvent

    - source: RMReview
      target: DocumentReview
      event: DocumentReviewEvent

    - source: DocumentReview
      target: Credit
      event: CreditEvent

    - source: Credit
      target: SDC
      event: SDCEvent

    - source: SDC
      target: WelcomeLetter
      event: WelcomeLetterEvent


#logging:
#  level:
#    org:
#      springframework:
#        statemachine: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  metrics:
    export:
      atlas:
        enabled: false


  server:
    port: 8080
